-- Phase 2: Full catalogue pricing settings, component minimums, quantity weights, and multipliers
insert into pricing_settings (key, value, description, category) values
  ('component_min_garage_doors', '22000', 'Minimum project amount for garage doors (cents)', 'component_min'),
  ('component_min_shutters', '18000', 'Minimum project amount for window shutters (cents)', 'component_min'),
  ('component_min_plaster_render', '35000', 'Minimum project amount for plaster / render (cents)', 'component_min'),
  ('component_min_pressure_cleaning', '20000', 'Minimum project amount for pressure cleaning (cents)', 'component_min'),
  ('component_min_spray_painting', '24000', 'Minimum project amount for spray painting (cents)', 'component_min'),

  ('quantity_weight_garage_doors', '19000', 'Price weight per garage door (cents)', 'quantity_weight'),
  ('quantity_min_garage_doors', '1', 'Minimum garage doors quantity', 'quantity_min'),
  ('quantity_weight_shutters', '8500', 'Price weight per shutter (cents)', 'quantity_weight'),
  ('quantity_min_shutters', '2', 'Minimum shutters quantity', 'quantity_min'),
  ('quantity_weight_plaster_render', '3200', 'Price weight per m² of plaster / render (cents)', 'quantity_weight'),
  ('quantity_min_plaster_render', '10', 'Minimum plaster / render m²', 'quantity_min'),
  ('quantity_weight_pressure_cleaning', '1500', 'Price weight per m² of pressure cleaning (cents)', 'quantity_weight'),
  ('quantity_min_pressure_cleaning', '15', 'Minimum pressure cleaning m²', 'quantity_min'),
  ('quantity_weight_spray_painting', '12000', 'Price weight per spray painting item (cents)', 'quantity_weight'),
  ('quantity_min_spray_painting', '1', 'Minimum spray painting items', 'quantity_min'),

  ('service_factor_paint_garage_doors', '0.95', 'Service factor: paint garage doors', 'service_factors'),
  ('service_factor_paint_shutters', '0.9', 'Service factor: paint shutters', 'service_factors'),
  ('service_factor_plaster_render_work', '1.25', 'Service factor: plaster / render work', 'service_factors'),
  ('service_factor_pressure_clean', '0.65', 'Service factor: pressure cleaning', 'service_factors'),
  ('service_factor_spray_paint_items', '0.9', 'Service factor: spray paint items', 'service_factors'),

  ('wall_coats_1_coat_multiplier', '0.75', 'Wall coats: 1 coat', 'component_options'),
  ('wall_coats_2_coats_multiplier', '1.0', 'Wall coats: 2 coats', 'component_options'),
  ('wall_coats_3_coats_multiplier', '1.3', 'Wall coats: 3 coats', 'component_options'),
  ('wall_condition_good_multiplier', '1.0', 'Wall condition: good', 'component_options'),
  ('wall_condition_minor_multiplier', '1.15', 'Wall condition: minor repairs', 'component_options'),
  ('wall_condition_renovation_multiplier', '1.35', 'Wall condition: renovation required', 'component_options'),
  ('wall_issue_none_multiplier', '1.0', 'Wall issue: none', 'component_options'),
  ('wall_issue_mould_multiplier', '1.25', 'Wall issue: mould', 'component_options'),
  ('wall_issue_nicotine_multiplier', '1.2', 'Wall issue: nicotine', 'component_options'),
  ('wall_issue_water_damage_multiplier', '1.3', 'Wall issue: water damage', 'component_options'),

  ('ceiling_coats_1_coat_multiplier', '0.75', 'Ceiling coats: 1 coat', 'component_options'),
  ('ceiling_coats_2_coats_multiplier', '1.0', 'Ceiling coats: 2 coats', 'component_options'),
  ('ceiling_coats_3_coats_multiplier', '1.3', 'Ceiling coats: 3 coats', 'component_options'),
  ('ceiling_condition_good_multiplier', '1.0', 'Ceiling condition: good', 'component_options'),
  ('ceiling_condition_minor_multiplier', '1.15', 'Ceiling condition: minor repairs', 'component_options'),
  ('ceiling_condition_renovation_multiplier', '1.35', 'Ceiling condition: renovation required', 'component_options'),

  ('window_type_standard_multiplier', '1.0', 'Window type: standard', 'component_options'),
  ('window_type_large_multiplier', '1.4', 'Window type: large', 'component_options'),
  ('window_type_skylight_multiplier', '1.25', 'Window type: skylight', 'component_options'),
  ('window_material_wood_multiplier', '1.05', 'Window material: wood', 'component_options'),
  ('window_material_metal_multiplier', '1.0', 'Window material: metal', 'component_options'),
  ('window_material_plastic_multiplier', '0.95', 'Window material: plastic', 'component_options'),
  ('window_sides_inside_multiplier', '0.65', 'Window painting: inside only', 'component_options'),
  ('window_sides_outside_multiplier', '0.65', 'Window painting: outside only', 'component_options'),
  ('window_sides_both_multiplier', '1.0', 'Window painting: both sides', 'component_options'),
  ('window_condition_good_multiplier', '1.0', 'Window condition: good', 'component_options'),
  ('window_condition_minor_multiplier', '1.15', 'Window condition: minor repairs', 'component_options'),
  ('window_condition_renovation_multiplier', '1.35', 'Window condition: renovation required', 'component_options'),

  ('radiator_type_panel_multiplier', '1.0', 'Radiator type: panel', 'component_options'),
  ('radiator_type_column_multiplier', '1.35', 'Radiator type: column', 'component_options'),
  ('radiator_condition_good_multiplier', '1.0', 'Radiator condition: good', 'component_options'),
  ('radiator_condition_minor_multiplier', '1.15', 'Radiator condition: minor repairs', 'component_options'),
  ('radiator_condition_renovation_multiplier', '1.35', 'Radiator condition: renovation required', 'component_options'),

  ('baseboard_material_wood_multiplier', '1.0', 'Skirting board material: wood', 'component_options'),
  ('baseboard_material_mdf_multiplier', '0.9', 'Skirting board material: mdf', 'component_options'),
  ('baseboard_material_other_multiplier', '0.95', 'Skirting board material: other', 'component_options'),
  ('baseboard_condition_good_multiplier', '1.0', 'Skirting board condition: good', 'component_options'),
  ('baseboard_condition_minor_multiplier', '1.15', 'Skirting board condition: minor touch-up', 'component_options'),
  ('baseboard_condition_renovation_multiplier', '1.3', 'Skirting board condition: renovation required', 'component_options'),

  ('stair_material_wood_multiplier', '1.05', 'Stair material: wood', 'component_options'),
  ('stair_material_metal_multiplier', '1.0', 'Stair material: metal', 'component_options'),
  ('stair_material_concrete_multiplier', '0.95', 'Stair material: concrete', 'component_options'),
  ('stair_scope_steps_only_multiplier', '0.75', 'Stair scope: steps only', 'component_options'),
  ('stair_scope_steps_railing_multiplier', '1.0', 'Stair scope: steps and railing', 'component_options'),
  ('stair_condition_good_multiplier', '1.0', 'Stair condition: good', 'component_options'),
  ('stair_condition_minor_multiplier', '1.15', 'Stair condition: minor sanding', 'component_options'),
  ('stair_condition_renovation_multiplier', '1.35', 'Stair condition: renovation required', 'component_options'),

  ('facade_surface_render_multiplier', '1.0', 'Facade surface: render / plaster', 'component_options'),
  ('facade_surface_wood_multiplier', '1.15', 'Facade surface: wood', 'component_options'),
  ('facade_surface_concrete_multiplier', '0.95', 'Facade surface: concrete', 'component_options'),
  ('facade_surface_mixed_multiplier', '1.1', 'Facade surface: mixed', 'component_options'),
  ('facade_condition_good_multiplier', '1.0', 'Facade condition: good', 'component_options'),
  ('facade_condition_minor_multiplier', '1.15', 'Facade condition: minor cracks', 'component_options'),
  ('facade_condition_renovation_multiplier', '1.35', 'Facade condition: renovation required', 'component_options'),
  ('scaffolding_not_sure_multiplier', '1.0', 'Scaffolding: to evaluate', 'component_options'),
  ('scaffolding_yes_multiplier', '1.3', 'Scaffolding: needed', 'component_options'),
  ('scaffolding_no_multiplier', '0.9', 'Scaffolding: not needed', 'component_options'),

  ('garage_door_material_metal_multiplier', '1.0', 'Garage door material: metal', 'component_options'),
  ('garage_door_material_wood_multiplier', '1.15', 'Garage door material: wood', 'component_options'),
  ('garage_door_sides_outside_multiplier', '0.75', 'Garage door painting: outside only', 'component_options'),
  ('garage_door_sides_both_multiplier', '1.0', 'Garage door painting: both sides', 'component_options'),
  ('garage_door_condition_good_multiplier', '1.0', 'Garage door condition: good', 'component_options'),
  ('garage_door_condition_minor_multiplier', '1.15', 'Garage door condition: minor sanding', 'component_options'),
  ('garage_door_condition_renovation_multiplier', '1.35', 'Garage door condition: renovation required', 'component_options'),

  ('shutter_material_wood_multiplier', '1.1', 'Shutter material: wood', 'component_options'),
  ('shutter_material_metal_multiplier', '1.0', 'Shutter material: metal', 'component_options'),
  ('shutter_sides_both_sides_multiplier', '1.0', 'Shutter painting: both sides', 'component_options'),
  ('shutter_sides_one_side_multiplier', '0.65', 'Shutter painting: front only', 'component_options'),
  ('shutter_condition_good_multiplier', '1.0', 'Shutter condition: good', 'component_options'),
  ('shutter_condition_minor_multiplier', '1.15', 'Shutter condition: minor preparation', 'component_options'),
  ('shutter_condition_renovation_multiplier', '1.35', 'Shutter condition: renovation required', 'component_options'),

  ('plaster_type_interior_multiplier', '1.0', 'Plaster type: interior', 'component_options'),
  ('plaster_type_exterior_multiplier', '1.25', 'Plaster type: exterior', 'component_options'),
  ('plaster_type_repair_multiplier', '0.9', 'Plaster type: repair', 'component_options'),
  ('plaster_condition_good_multiplier', '0.95', 'Plaster condition: sound surface', 'component_options'),
  ('plaster_condition_minor_multiplier', '1.0', 'Plaster condition: minor defects', 'component_options'),
  ('plaster_condition_renovation_multiplier', '1.3', 'Plaster condition: significant damage', 'component_options'),

  ('cleaning_surface_facade_multiplier', '1.0', 'Cleaning surface: facade', 'component_options'),
  ('cleaning_surface_terrace_multiplier', '0.9', 'Cleaning surface: terrace', 'component_options'),
  ('cleaning_surface_driveway_multiplier', '0.95', 'Cleaning surface: driveway', 'component_options'),
  ('cleaning_surface_other_multiplier', '1.0', 'Cleaning surface: other', 'component_options'),
  ('cleaning_intensity_standard_multiplier', '1.0', 'Cleaning intensity: standard', 'component_options'),
  ('cleaning_intensity_deep_multiplier', '1.35', 'Cleaning intensity: deep treatment', 'component_options'),

  ('spray_item_type_doors_multiplier', '1.0', 'Spray item: doors / panels', 'component_options'),
  ('spray_item_type_radiators_multiplier', '1.05', 'Spray item: radiators / metal', 'component_options'),
  ('spray_item_type_cabinetry_multiplier', '1.25', 'Spray item: cabinetry', 'component_options'),
  ('spray_item_type_other_multiplier', '1.0', 'Spray item: other', 'component_options'),
  ('spray_finish_satin_multiplier', '1.0', 'Spray finish: satin', 'component_options'),
  ('spray_finish_high_gloss_multiplier', '1.25', 'Spray finish: high gloss', 'component_options'),
  ('spray_finish_standard_multiplier', '0.95', 'Spray finish: standard matte', 'component_options')
on conflict (key) do nothing;
